.TH "DaySegments" 3 "Tue Sep 13 2022" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DaySegments
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDaySegment\fP"
.br
.RI "A day segment is a part of a day, specifically either night, morning, afternoon or evening\&.  "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
